### ISSUE TITLE
Debian/Ubuntu (others) shipped a very old hardinfo for a long time

### ISSUE THREAD

**Issue by bp0** [lpereira/hardinfo#163]
There are many bugs reported for the old version (5.1, 2009) that are likely fixed by now.
* https://bugs.launchpad.net/ubuntu/+source/hardinfo

Please build from source or try the newer version in Debian unstable before reporting bugs.

**Comment by mckaygerhard** [comment]
umm open a issue to notify solved situation a dont think so .. why open a issue for tht?

**Comment by bp0** [comment]
It is a meta issue. This issue can be referred to in bug reports against old packages, as I did in #17, and #26.

**Comment by mckaygerhard** [comment]
i think that issues are solved..  i provided update hardinfo packages in venenux repositoryes.. debian has a impossible way to become mantainer and the mentors process are mixed too much with a network connection..

**Comment by mckaygerhard** [comment]
Ready to test packages for Debian 7,8,9 and Devuan 1 and VenenuX 1.0

https://build.opensuse.org/package/show/home:vegnuli/hardinfo (x86, amd64)

for Debian << 7 y venenux 0.X

http://intranet1.net.ve/venenux/experimental/hardinfo/ (x86 solamente)
http://venenuxrepo.fundacite-aragua.gob.ve/experimental/hardinfo/ (x86 solamente)

**Comment by mckaygerhard** [comment]
due there now packages available Ready to test, this issue can be closed..

i will added a debian directory that in conjuntion with susebuildservice will automatically update package every commit

**Comment by bp0** [comment]
This issue exists be referred to in bug reports here and elsewhere. It is not fixed until distributions are shipping updated packages for hardinfo. The current releases of Debian and all of it's derivatives, are still shipping the very old packages. It is not fixed, it should not be closed. It should be open until at least Ubuntu 17.10 in October, and perhaps through the next Ubuntu LTS in April.

**Comment by lpereira** [comment]
I'm maintaining a Ubuntu PPA for HardInfo built from Git sources, which should make life easier for those wanting to try a new version out: https://launchpad.net/~lafp/+archive/ubuntu/hardinfo

**Comment by TomaszGasior** [comment]
HardInfo from master is available unofficially for Fedora users from my own COPR repo here: https://copr.fedorainfracloud.org/coprs/tomaszgasior/mushrooms/

**Comment by hamishmb** [comment]
> I'm maintaining a Ubuntu PPA for HardInfo built from Git sources, which should make life easier for those wanting to try a new version out: https://launchpad.net/~lafp/+archive/ubuntu/hardinfo

This doesn't seem to be up to date anymore - have you moved it somewhere else?
